### ISSUE TITLE
Test app on iOS device

### ISSUE THREAD

**Issue by emmanuelroussel** [emmanuelroussel/stockpile-app#114] opened 2017-03-06 17:06 UTC
Both try by installing with the CLI and Ionic View.

Ken had problems with the scanner. Not sure if this is a problem with iOS or Ionic View.

**Comment by AdamVig** [comment] 2017-03-08 22:26
The app works fine in Ionic View.

When installed with XCode, however, it shows the splash screen then shows a blank white screen. I will investigate further.

**Comment by AdamVig** [comment] 2017-03-17 16:11
The white screen problem was caused by Cordova plugins not being installed, which I solved for the future in #131.

Now, when I launch the app on either the iOS emulator or device, I get some normal console output along with a couple of fatal errors:
![image](https://cloud.githubusercontent.com/assets/5354752/24050809/79a11ee0-0b06-11e7-9061-99abb1817ce2.png)

It seems that the URLs are not being constructed properly, so the HTTP provider is defaulting to using the `file://` protocol.

After further testing, I have identified that the problem is the `ApiUrl` constant being set to a relative URL (`/api`). This works fine for development in-browser, where we use the Ionic proxy to avoid CORS issues, but the proxy does not work on the device ([source](http://stackoverflow.com/questions/33813893/ionic-proxy-works-on-ionic-serve-not-on-ios-simulator-or-device)).

We may be able to use [Ionic's platform detection](http://ionicframework.com/docs/v2/api/platform/Platform/) to dynamically change the API URL based on the current platform. This would require changing the structure of the `constants` file to be more like a component. Another option is to make Webpack change the URL based on the build target. @emmanuelroussel any feedback on these options?

For now, I will hard code the correct URL into place and use that for testing purposes.

**Comment by AdamVig** [comment] 2017-03-17 16:16
Once I hard-coded the URL in place, the app worked flawlessly (including the barcode scanner and toasts).

**Comment by emmanuelroussel** [comment] 2017-03-17 19:34
Webpack would make more sense, but we currently can't change the config ([related issue on ionic-app-scripts repo](https://github.com/driftyco/ionic-app-scripts/issues/760)). The other temporary solutions require rollup which is overkill for what we need and requires lots of setup or copy and pasting Ionic's webpack config and changing it manually which is also .

Not sure what the best solution is. Maybe we can change the url from a constant to a function that returns the appropriate url depending on the platform as you mentioned.

**Comment by AdamVig** [comment] 2017-03-17 20:12
Good idea. Created #134 to fix this. Assign to me if you want me to tackle it.

**Closed by AdamVig** 2017-03-17 20:12 UTC
Labels: chore
